<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-oop_mvc_id_20260205_b-ee9f8bd5-6c90-4db1-87ce-fd844b319916</UserSecretsId>
    <RootNamespace>oop_mvc_id_20260205_b</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="9.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.12" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="9.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.12" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.12" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="9.0.12" />
  </ItemGroup>

</Project>
